#!/bin/bash

# Define the source directory (inside mounted dmg volume)
SOURCE="/Volumes/Higu_Ch1_Kor/Contents"
# Define the destination directory
DESTINATION="$HOME/Library/Application Support/Steam/steamapps/common/Higurashi When They Cry/HigurashiEp01.app/Contents"

# Ensure trailing slash for rsync behavior consistency
SOURCE="${SOURCE}/"
DESTINATION="${DESTINATION}/"

# Description of the operation
echo "macOS용 쓰르라미 울 적에 한글패치 인스톨러"
echo "인스톨러 제작자: Montmorency (https://github.com/s485lee/Higurashi_Korean_Mac)"
echo "인스톨러 제작에 도움을 주신 분: Côte-Vertu"
echo "macOS용 쓰르라미 울 적에 한글패치는 Steam판을 지원합니다."
echo "한글패치를 설치하려면 y 키를. 취소하려면 n 키를 눌러 주세요. (y/n)"

# Wait for user confirmation
read -r user_confirm

if [[ $user_confirm == "y" || $user_confirm == "Y" ]]; then
    # Check if the source directory exists
    if [ -d "$SOURCE" ]; then
        # Using rsync to copy and replace files without deleting anything in the destination
        rsync -av "$SOURCE" "$DESTINATION"
        echo "하우~☆! 오모치카에리~!."
        echo "한글패치가 성공적으로 적용되었습니다. 게임을 Steam에서 실행해 주세요. 니파~☆"        
        # Wait for the user to press enter before exiting
        read -p "Return 이나 Enter 키를 눌러 패치 인스톨러를 종료할 까나, 까나...?"
    else
        echo "한글패치 파일을 찾을 수 없습니다."
        # Wait for the user to press enter before exiting
        read -p "Return 이나 Enter 키를 누르면 패치 인스톨러를 종료합니다..."
    fi
else
    echo "작업이 취소되었습니다."
    # Wait for the user to press enter before exiting
    read -p "Return 이나 Enter 키를 누르면 패치 인스톨러를 종료합니다..."
fi