#!/bin/bash

# Define the source directory (inside mounted dmg volume)
SOURCE="/Volumes/Higu_Ch1_Kor/Contents"
# Define the destination directory
DESTINATION="$HOME/Library/Application Support/Steam/steamapps/common/Higurashi When They Cry/HigurashiEp01.app/Contents"
#Define the directory for steamgrid images
GRID_IMAGES_SOURCE="/path/to/grid/images"

# Ensure trailing slash for rsync behavior consistency
SOURCE="${SOURCE}/"
DESTINATION="${DESTINATION}/"
GRID_IMAGES_SOURCE="${GRID_IMAGES_SOURCE}/"

# Description of the operation
echo "macOS용 쓰르라미 울 적에 한글패치 인스톨러"
echo "인스톨러 제작자: Montmorency (https://github.com/s485lee/Higurashi_Korean_Mac)"
echo "인스톨러 제작에 도움을 주신 분: Côte-Vertu"
echo "macOS용 쓰르라미 울 적에 한글패치는 Steam판을 지원합니다."
echo "한글패치를 설치하려면 y 키를. 취소하려면 n 키를 눌러 주세요. (y/n)"

# Wait for user confirmation
read -r user_confirm

if [[ $user_confirm == "y" || $user_confirm == "Y" ]]; then
    if [ -d "$SOURCE" ]; then
        rsync -av "$SOURCE" "$DESTINATION"
        echo "한글패치가 성공적으로 적용되었습니다."
        
        # New feature to install steamgrid images
        USERDATA_DIR="$HOME/Library/Application Support/Steam/userdata/"
        FOUND_USER_DIR=false # Flag to check if any user directory has been found
        for USER_DIR in "$USERDATA_DIR"*/; do
            if [[ $(basename "$USER_DIR") =~ ^[0-9]{8}$ ]]; then
                FOUND_USER_DIR=true # Found at least one user directory
                GRID_DESTINATION="${USER_DIR}config/grid/"
                mkdir -p "$GRID_DESTINATION" # Ensure the destination directory exists
                rsync -av "$GRID_IMAGES_SOURCE" "$GRID_DESTINATION"
                echo "Steamgrid 이미지가 성공적으로 설치되었습니다."
            fi
        done
        
        if [ "$FOUND_USER_DIR" = false ]; then
            echo "Steam 사용자 데이터 폴더를 찾을 수 없거나 유효한 Steam 사용자 ID가 없습니다."
        fi
        echo "하우~☆! 오모치카에리~!."
        echo "한글패치가 성공적으로 적용되었습니다. 게임을 Steam에서 실행해 주세요. 니파~☆"          
        read -p "Return 이나 Enter 키를 눌러 패치 인스톨러를 종료할 까나, 까나...?"
    else
        echo "한글패치 파일을 찾을 수 없습니다."
        read -p "Return 이나 Enter 키를 누르면 패치 인스톨러를 종료합니다..."
    fi
else
    echo "작업이 취소되었습니다."
    read -p "Return 이나 Enter 키를 누르면 패치 인스톨러를 종료합니다..."
fi